### ISSUE TITLE
root privileges 

### ISSUE THREAD

**Issue by ThaGuMath** [safenetwork-community/comnet-install#13]
I know this is for Ubuntu, but as a Debian 11/Bullseye user, I thought I'd give it a try.

The calls to sudo will not work in Debian unless the user's account is set up in sudoers - not in issue in Ubuntu.

Sorry - a problem for the future!!

**Comment by willief** [comment]
#WontFix

My excuse is that this script is KISS for Ubuntu users.  Anyone advanced enough to prefer Debian over Ubuntu will be able to sort this themselves by adding their account to sudoers group
